version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    image: node:18
    container_name: auth-service
    working_dir: /app
    volumes:
      - ./services/auth-service:/app
    command: sh -c "npm install && npm run start"
    ports:
      - "3001:3001"
  order-service:
    image: node:18
    container_name: order-service
    working_dir: /app
    volumes:
      - ./services/order-service:/app
    command: sh -c "npm install && npm run start"
    ports:
      - "3002:3002"
  user-service:
    image: node:18
    container_name: user-service
    working_dir: /app
    volumes:
      - ./services/user-service:/app
    command: sh -c "npm install && npm run start"
    ports:
      - "3003:3003"
  gateway:
    image: node:18
    container_name: gateway
    working_dir: /app
    volumes:
      - ./gateway:/app
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
