version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # <<< THÊM HEALTHCHECK CHO POSTGRES
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    image: node:18
    container_name: auth-service
    working_dir: /app
    volumes:
      - ./services/auth-service:/app
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    command: sh -c "npm install && npm run build && npx prisma migrate deploy && npm run start"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"
  order-service:
    image: node:18
    container_name: order-service
    working_dir: /app
    volumes:
      - ./services/order-service:/app
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    command: sh -c "npm install && npm run build && npx prisma migrate deploy && npm run start"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3002:3002"
  user-service:
    image: node:18
    container_name: user-service
    working_dir: /app
    volumes:
      - ./services/user-service:/app
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    command: sh -c "npm install && npm run build && npx prisma migrate deploy && npm run start"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3003:3003"
  product-service:
    image: node:18
    container_name: product-service
    working_dir: /app
    volumes:
      # Giả sử thư mục code là ./services/product-service
      - ./services/product-service:/app
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    command: sh -c "npm install && npm run build && npx prisma migrate deploy && npm run start"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3004:3004" # Chạy trên cổng 3004
  gateway:
    image: node:18
    container_name: gateway
    working_dir: /app
    volumes:
      - ./gateway:/app
    command: sh -c "npm install && npm run build && npm run start"
    depends_on:
      - auth-service
      - order-service
      - user-service
    ports:
      - "3000:3000"

volumes:
  postgres_data:
